#!/usr/bin/env python3
"""Skillboard — static tabbed dashboard of the agent setup (skills, hooks,
memory, plans, plan usage, setup docs). Stdlib only; every collector
fail-opens to a placeholder. Auto-regenerated by the plugin's SessionStart
hook; manual: python3 ~/.claude/scripts/setup-dashboard.py [--open]
Config: ~/.claude/skillboard.json (see skillboard-init).
"""
import glob
import html
import json
import os
import re
import shutil
import sqlite3
import sys
import time

H = os.path.expanduser("~")
OUT = os.path.join(H, ".claude", "skillboard.html")


def _cfg():
    try:
        with open(os.path.join(H, ".claude", "skillboard.json"), encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


CFG = _cfg()
DEV = os.path.expanduser(CFG.get("dev_root") or "~/development")
BRAIN = os.path.expanduser(CFG.get("brain_dir") or "~/remember")
REPO = CFG.get("repo") or ""  # "owner/skillboard" -> enables copy-link cards
TRIGGER = int(CFG.get("corpus_trigger") or 50)
PLUGIN_GLOB = os.path.join(H, ".claude", "plugins", "cache", "skillboard", "skillboard", "*")


def esc(s):
    return html.escape(str(s))


def safe(fn, default):
    try:
        return fn()
    except Exception:
        return default


def mem_stats():
    db = os.path.join(H, ".claude", "memory-index.db")
    con = sqlite3.connect(db)
    by = dict(con.execute("SELECT source, count(*) FROM mem GROUP BY source"))
    total = sum(by.values())
    con.close()
    age = time.time() - os.path.getmtime(db)
    return by, total, age


def _scan_skills(root):
    out = []
    if not os.path.isdir(root):
        return out
    for d in sorted(os.listdir(root)):
        p = os.path.join(root, d, "SKILL.md")
        if not os.path.isfile(p):
            continue
        desc = ""
        with open(p, encoding="utf-8", errors="replace") as f:
            txt = f.read(4000)
        m = re.search(r"^description:\s*>?-?\s*\"?(.+?)\"?$", txt, re.M)
        if m:
            desc = m.group(1)
        out.append((d, desc[:110] + ("…" if len(desc) > 110 else ""), p))
    return out


def skills():
    """(plugin_skills, local_skills) — plugin ones from the newest cache dir."""
    caches = sorted(glob.glob(PLUGIN_GLOB))
    plug = _scan_skills(os.path.join(caches[-1], "skills")) if caches else []
    return plug, _scan_skills(os.path.join(H, ".claude", "skills"))


def settings():
    with open(os.path.join(H, ".claude", "settings.json"), encoding="utf-8") as f:
        return json.load(f)


def hooks_rows(cfg):
    rows = []
    for event, groups in (cfg.get("hooks") or {}).items():
        n = sum(len(g.get("hooks", [])) for g in groups)
        rows.append((event, n))
    return sorted(rows, key=lambda r: -r[1])


def maintenance():
    p = os.path.join(H, ".local", "state", "remember", "processed-claude-code")
    days = (time.time() - os.path.getmtime(p)) / 86400
    return days, max(0.0, 7 - days)


def brain():
    b = BRAIN
    def count(sub, rec=False):
        base = os.path.join(b, sub)
        if not os.path.isdir(base):
            return 0
        if not rec:
            return len([f for f in os.listdir(base) if f.endswith(".md")])
        return sum(len([f for f in fs if f.endswith(".md")]) for _, _, fs in os.walk(base))
    beliefs = 0
    m = safe(lambda: open(os.path.join(b, "Persona.md"), encoding="utf-8").read(), "")
    sec = re.search(r"## Top Beliefs\n(.*?)\n## ", m, re.S)
    if sec:
        beliefs = len(re.findall(r"^\d+\.", sec.group(1), re.M))
    return {"Notes": count("Notes"), "Journal": count("Journal"),
            "Projects": count("Projects", rec=True), "Patterns": count("Resources/patterns"),
            "Top beliefs": beliefs}


def plans():
    """Discover plan dirs under dev_root: any `.doc/` or `doc/plans/` (depth ≤4)."""
    prune = {".git", "node_modules", "vendor", ".venv", "venv", "storage", "dist", "build"}
    dirs = []
    depth0 = DEV.rstrip(os.sep).count(os.sep)
    for root, subdirs, _ in os.walk(DEV):
        if root.count(os.sep) - depth0 >= 6:
            subdirs[:] = []
            continue
        subdirs[:] = [d for d in subdirs if d not in prune]
        if os.path.basename(root) == ".doc" or root.endswith(os.path.join("doc", "plans")):
            dirs.append(root)
            subdirs[:] = []
    found = []
    for d in dirs:
        if not os.path.isdir(d):
            continue
        for f in os.listdir(d):
            if not f.endswith(".md"):
                continue
            p = os.path.join(d, f)
            status = ""
            head = safe(lambda: open(p, encoding="utf-8", errors="replace").read(2000), "")
            m = re.search(r"\*\*Status:?\*\*:?\s*(.+)", head)
            if m:
                status = m.group(1)[:90]
            found.append((os.path.getmtime(p), f, status, p))
    return [x[1:] for x in sorted(found, reverse=True)[:12]]


def bar(pct, hue="var(--blue)"):
    pct = max(2, min(100, int(pct)))
    return (f'<div class="meter"><div class="meter-fill" '
            f'style="width:{pct}%;background:{hue}"></div></div>')


def vslink(path, label):
    return f'<a class="mono flink" href="vscode://file{esc(path)}" title="open in VS Code">{esc(label)}</a>'


def plan_usage():
    """Claude plan usage %, same source as the /usage panel. OAuth token is
    read from Keychain in-process and used for one HTTPS call — it is never
    written to the page or disk. Returns [] when offline/no token (panel hides)."""
    import subprocess
    import urllib.request
    raw = subprocess.run(
        ["security", "find-generic-password", "-s", "Claude Code-credentials", "-w"],
        capture_output=True, text=True, timeout=5).stdout
    tok = json.loads(raw).get("claudeAiOauth", {}).get("accessToken", "")
    if not tok:
        return []
    req = urllib.request.Request(
        "https://api.anthropic.com/api/oauth/usage",
        headers={"Authorization": f"Bearer {tok}", "anthropic-beta": "oauth-2025-04-20"})
    with urllib.request.urlopen(req, timeout=5) as r:
        d = json.load(r)
    out = []
    for lim in d.get("limits") or []:
        if lim.get("percent") is None:
            continue
        label = {"session": "Session (5h)", "weekly_all": "Weekly · all models",
                 "weekly_opus": "Weekly · Opus", "weekly_fable": "Weekly · Fable"}.get(
                    lim.get("kind"), lim.get("kind", "?"))
        reset = ""
        m = re.match(r"(\d+-\d+-\d+)T(\d+:\d+)", lim.get("resets_at") or "")
        if m:
            ts = time.mktime(time.strptime(f"{m.group(1)} {m.group(2)}", "%Y-%m-%d %H:%M"))
            ts -= time.timezone  # value is UTC; show local
            reset = "resets " + time.strftime("%a %H:%M", time.localtime(ts))
        out.append((label, int(lim.get("percent") or 0), lim.get("severity", "normal"), reset))
    return out


RECOMMENDED = [
    # (name, kind, detect-key/cli, benefit, install command)
    ("superpowers", "plugin", "superpowers@",
     "TDD, brainstorming, plan-execution process skills",
     "/plugin install superpowers@claude-plugins-official"),
    ("caveman", "plugin", "caveman@",
     "~65-75% fewer output tokens, terse mode",
     "/plugin marketplace add JuliusBrussee/caveman → /plugin install caveman@caveman"),
    ("remember", "plugin", "remember@",
     "personal second brain: capture + weekly session distillation",
     "/plugin marketplace add remember-md/marketplace → /plugin install remember@remember-md"),
    ("token-optimizer", "plugin", "token-optimizer@",
     "usage trends, quality scores, optimization audit + its own dashboard",
     "/plugin marketplace add alexgreensh/token-optimizer → /plugin install token-optimizer@alexgreensh-token-optimizer"),
    ("security-guidance", "plugin", "security-guidance@",
     "flags insecure patterns as you code",
     "/plugin install security-guidance@claude-plugins-official"),
    ("context7", "plugin", "context7@",
     "live library docs lookup",
     "/plugin install context7@claude-plugins-official"),
    ("frontend-design", "plugin", "frontend-design@",
     "non-templated UI design direction",
     "/plugin install frontend-design@claude-plugins-official"),
    ("rtk", "cli", "rtk",
     "60-90% smaller bash outputs (PreToolUse rewrite)",
     "cargo install rtk  # or see rtk repo"),
    ("codegraph", "cli", "codegraph",
     "code knowledge graph: callers/impact/architecture",
     "see codegraph install docs; then `codegraph init -i` per repo"),
    ("code-review-graph", "cli", "code-review-graph",
     "change-impact + review context on every edit",
     "see code-review-graph install docs; `code-review-graph build` per repo"),
    ("gh", "cli", "gh",
     "GitHub CLI — needed for private-repo plugin updates",
     "brew install gh && gh auth login"),
]


def recommended_status(cfg):
    enabled = cfg.get("enabledPlugins") or {}
    rows = []
    for name, kind, key, benefit, cmd in RECOMMENDED:
        if kind == "plugin":
            ok = any(k.startswith(key) and v for k, v in enabled.items())
        else:
            ok = shutil.which(key) is not None
        rows.append((name, benefit, cmd, ok))
    return rows


PREV = os.path.join(H, ".claude", ".setup-dashboard-prev.json")


def load_prev():
    with open(PREV, encoding="utf-8") as f:
        return json.load(f)


def save_snapshot(snap):
    with open(PREV, "w", encoding="utf-8") as f:
        json.dump(snap, f)


def delta(prev, key, cur):
    """mae8-style delta: 'was N →' when the number moved since last regen."""
    old = (prev or {}).get(key)
    if old is None or old == cur:
        return ""
    return f'<span class="delta">{esc(old)} →</span> '


def plan_pill(status):
    s = status.lower()
    if not status:
        return ""
    if "built" in s or "✅" in status or "done" in s or "complete" in s:
        return '<span class="pill ok">SHIPPED</span> '
    if "deferred" in s or "planning" in s:
        return '<span class="pill">PLANNED</span> '
    return ""


def main():
    by, mem_total, idx_age = safe(mem_stats, ({}, 0, 0))
    corpus = by.get("auto-memory", 0) + by.get("brain", 0)
    plug_sk, loc_sk = safe(skills, ([], []))
    sk = plug_sk + loc_sk
    cfg = safe(settings, {})
    hk = safe(lambda: hooks_rows(cfg), [])
    plugins = [k.split("@")[0] for k, v in (cfg.get("enabledPlugins") or {}).items() if v]
    days_ago, due_in = safe(maintenance, (None, None))
    br = safe(brain, {})
    pl = safe(plans, [])
    gen_epoch = int(time.time())
    now = time.strftime("%Y-%m-%d %H:%M")

    prev = safe(load_prev, {})
    n_hooks = sum(n for _, n in hk)
    safe(lambda: save_snapshot({"skills": len(sk), "hooks": n_hooks,
                                "plugins": len(plugins), "mem": mem_total,
                                "corpus": corpus, "ts": gen_epoch}), None)

    usage = safe(plan_usage, [])
    hue = {"normal": "var(--blue)", "warning": "var(--warn)", "critical": "var(--crit)"}
    usage_rows = "".join(
        f'<tr><td>{esc(lb)}</td><td class="num">{p}%</td>'
        f'<td class="cell-bar">{bar(p, hue.get(sev, "var(--blue)"))}</td>'
        f'<td class="rst dim">{esc(rs)}</td></tr>'
        for lb, p, sev, rs in usage)
    usage_html = (f'<h2>Plan Usage</h2><table>{usage_rows}</table>'
                  '<p class="note">Live from the same source as /usage · Pro plan</p>'
                  if usage else "")

    # hero status banner (token-optimizer style): one-line health verdict
    issues = []
    for lb, p, sev, _ in usage:
        if sev == "critical":
            issues.append(f"{lb} at {p}% — nearly maxed")
    if days_ago is None or days_ago > 7:
        issues.append("weekly /remember:process overdue")
    if idx_age > 2 * 86400:
        issues.append("memory index stale >2d")
    if corpus >= TRIGGER:
        issues.append(f"memory corpus hit {corpus}/{TRIGGER} — SQLite plan trigger")
    if issues:
        banner = ('<div class="banner warn-b">&#9888; ' +
                  " · ".join(esc(i) for i in issues) + "</div>")
    else:
        banner = ('<div class="banner ok-b">&#10003; Setup healthy — memory fresh, '
                  'maintenance done, no overdue items.</div>')

    tiles = [
        ("Global skills", len(sk), "", "skills"),
        ("Hooks installed", n_hooks, f"{len(hk)} events", "hooks"),
        ("Plugins on", len(plugins), "", "plugins"),
        ("Memory files indexed", mem_total, f"index refreshed {int(idx_age/60)}m ago", "mem"),
    ]
    tiles_html = "".join(
        f'<div class="tile"><div class="tile-num">{delta(prev, key, v)}{esc(v)}</div>'
        f'<div class="tile-label">{esc(k)}</div>'
        f'<div class="tile-sub">{esc(s)}</div></div>' for k, v, s, key in tiles)

    src_rows = "".join(
        f'<tr><td>{esc(s)}</td><td class="num">{n}</td>'
        f'<td class="cell-bar">{bar(100*n/max(1,mem_total))}</td>'
        f'<td class="pct dim">{100*n//max(1,mem_total)}%</td></tr>'
        for s, n in sorted(by.items(), key=lambda x: -x[1]))

    trig_pct = 100 * corpus / TRIGGER
    maint = ("<span class='status ok'>&#10003; done recently</span>" if days_ago is not None and days_ago <= 7
             else "<span class='status warn'>&#9888; overdue — run /remember:process</span>")
    maint_sub = (f"last run {days_ago:.1f}d ago · next due in {due_in:.1f}d"
                 if days_ago is not None else "state unknown")

    def card(n, d, p):
        star = ' style="border-color:var(--acc)"' if n == "skillboard-init" else ""
        here = '<span class="pill" style="color:var(--acc);border-color:var(--acc)">START HERE</span> ' if n == "skillboard-init" else ""
        link = (f"https://github.com/{REPO}/blob/main/skills/{n}/SKILL.md" if REPO else p)
        return (f'<div class="card"{star}><div class="card-head">{here}'
                f'<span class="mono card-name">{esc(n)}</span>'
                f'<button class="copy" data-link="{esc(link)}" onclick="cp(this)">copy link</button></div>'
                f'<p class="dim card-desc">{esc(d)}</p>'
                f'<p class="card-url">{esc(link)}</p></div>')

    plug_cards = "".join(card(n, d, p) for n, d, p in plug_sk)
    skills_rows = "".join(
        f'<tr><td>{vslink(p, n)}</td><td class="dim">{esc(d)}</td></tr>' for n, d, p in loc_sk)

    ok_badge = '<span class="status ok">&#10003; installed</span>'
    no_badge = '<span class="status warn">not installed</span>'
    rec_rows = "".join(
        f'<tr><td class="mono">{esc(n)}</td>'
        f'<td>{ok_badge if ok else no_badge}</td>'
        f'<td class="dim">{esc(b)}</td>'
        f'<td class="mono inst">{esc(c)}</td></tr>'
        for n, b, c, ok in safe(lambda: recommended_status(cfg), []))

    features = [
        ("Memory index", "FTS5 search over all memory homes; refreshed each session start", "scripts/memory-index.py → ~/.claude/memory-index.db"),
        ("memory-recall skill", "answers 'what did we decide about X' in 2 tool calls", "skillboard:memory-recall"),
        ("Continuity hooks", "session start points agent at .doc plans + handoff.md; compact hooks preserve + restore plan state", "hooks/hooks.json"),
        ("Weekly maintenance reminder", "nags when /remember:process is >7 days old", "SessionStart hook, silent when fresh"),
        ("Skillboard dashboard", "this page — regenerated every session start", "scripts/setup-dashboard.py → ~/.claude/skillboard.html"),
        ("Plan usage panel", "live plan limits from the /usage source", "Overview tab; needs Keychain token, fail-open"),
        ("skillboard-init", "idempotent machine bootstrap: deps, config, shims, settings, CLAUDE.md sections", "/skillboard-init"),
    ]
    feat_rows = "".join(f'<tr><td>{esc(a)}</td><td class="dim">{esc(b)}</td>'
                        f'<td class="mono inst">{esc(c)}</td></tr>' for a, b, c in features)

    checklist = """<ol class="steps">
<li><span class="mono">gh auth login</span> — private repo, auth first</li>
<li>In Claude Code: <span class="mono">/plugin marketplace add &lt;user&gt;/skillboard</span></li>
<li><span class="mono">/plugin install skillboard@skillboard</span></li>
<li><span class="mono">/skillboard-init</span> — deps, config, shims, settings, CLAUDE.md</li>
<li>Add alias: <span class="mono">alias skillboard='python3 ~/.claude/scripts/setup-dashboard.py --open'</span></li>
</ol>
<p class="note">Config file: <span class="mono">~/.claude/skillboard.json</span> — keys: dev_root (repo scan root), brain_dir (remember brain, "" to disable), corpus_trigger (SQLite plan threshold), repo (owner/skillboard for the copy-link cards).</p>"""
    hooks_rows_html = "".join(f'<tr><td class="mono">{esc(e)}</td><td class="num">{n}</td></tr>'
                              for e, n in hk)
    brain_rows = "".join(f'<tr><td>{esc(k)}</td><td class="num">{v}</td></tr>' for k, v in br.items())
    plan_rows = "".join(
        f'<tr><td>{vslink(p, f)}</td><td class="dim">{plan_pill(s)}{esc(s)}</td></tr>'
        for f, s, p in pl)
    plugins_html = " ".join(f'<span class="chip">{esc(p)}</span>' for p in sorted(plugins))

    page = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Skillboard</title><style>
:root {{ --s1:#fcfcfb; --s2:#f1f1ef; --ink:#0b0b0b; --ink2:#52514e; --ink3:#8a887f;
  --line:#e2e1dc; --blue:#2a78d6; --ok:#008300; --warn:#c98500; --acc:#eb6834; --crit:#e34948; }}
@media (prefers-color-scheme: dark) {{ :root {{ --s1:#1a1a19; --s2:#232322; --ink:#fff;
  --ink2:#c3c2b7; --ink3:#8a887f; --line:#33332f; --blue:#3987e5; --ok:#1baf7a; --warn:#eda100; --acc:#d95926; --crit:#e66767; }} }}
:root[data-theme=light] {{ --s1:#fcfcfb; --s2:#f1f1ef; --ink:#0b0b0b; --ink2:#52514e;
  --line:#e2e1dc; --blue:#2a78d6; --ok:#008300; --warn:#c98500; --acc:#eb6834; --crit:#e34948; }}
:root[data-theme=dark] {{ --s1:#1a1a19; --s2:#232322; --ink:#fff; --ink2:#c3c2b7;
  --line:#33332f; --blue:#3987e5; --ok:#1baf7a; --warn:#eda100; --acc:#d95926; --crit:#e66767; }}
* {{ box-sizing:border-box; margin:0 }}
body {{ background:var(--s1); color:var(--ink); font:15px/1.5 -apple-system,'Segoe UI',sans-serif;
  max-width:1000px; margin:0 auto; padding:28px 20px 64px }}
header {{ display:flex; justify-content:space-between; align-items:baseline; margin-bottom:14px }}
h1 {{ font-size:20px; letter-spacing:.02em }}
h2 {{ font-size:12px; text-transform:uppercase; letter-spacing:.12em; color:var(--acc);
  font-weight:650; margin:26px 0 10px }}
.gen {{ color:var(--ink3); font-size:12px }}
.gen.stale {{ color:var(--warn); font-weight:600 }}
.banner {{ border-radius:8px; padding:10px 14px; font-size:13.5px; font-weight:600;
  margin-bottom:16px; border:1px solid }}
.banner.ok-b {{ color:var(--ok); border-color:var(--ok); background:color-mix(in srgb, var(--ok) 8%, transparent) }}
.banner.warn-b {{ color:var(--warn); border-color:var(--warn); background:color-mix(in srgb, var(--warn) 8%, transparent) }}
.delta {{ color:var(--ink3); font-size:15px; font-weight:400; text-decoration:line-through }}
.pill {{ display:inline-block; border:1px solid var(--line); color:var(--ink3);
  border-radius:99px; padding:0 8px; font-size:10px; letter-spacing:.06em; font-weight:650;
  vertical-align:1px }}
.pill.ok {{ color:var(--ok); border-color:var(--ok) }}
td.pct {{ width:5ch; text-align:right; font-size:12px }}
td.rst {{ width:15ch; text-align:right; font-size:12px; white-space:nowrap }}
.badge {{ display:inline-block; background:var(--s2); border:1px solid var(--line);
  border-radius:99px; padding:0 7px; font-size:10.5px; margin-left:6px; color:var(--ink2) }}
.badge.warn-d {{ color:var(--warn); border-color:var(--warn) }}
.cards {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(300px,1fr)); gap:12px }}
.card {{ background:var(--s2); border:1px solid var(--line); border-radius:10px; padding:12px 14px }}
.card-head {{ display:flex; align-items:center; gap:8px }}
.card-name {{ font-weight:650; flex:1 }}
.card-desc {{ font-size:12.5px; margin:6px 0 4px; display:-webkit-box; -webkit-line-clamp:3;
  -webkit-box-orient:vertical; overflow:hidden }}
.card-url {{ font-size:10.5px; color:var(--ink3); word-break:break-all; font-family:ui-monospace,Menlo,monospace }}
button.copy {{ background:var(--acc); color:#fff; border:none; border-radius:6px;
  padding:3px 10px; font-size:11px; font-weight:650; cursor:pointer }}
button.copy:active {{ opacity:.7 }}
.steps li {{ margin:6px 0 }}
.steps {{ padding-left:22px }}
td.inst {{ font-size:11px; max-width:34ch; white-space:normal; word-break:break-word }}
button#th {{ background:var(--s2); color:var(--ink2); border:1px solid var(--line);
  border-radius:6px; padding:4px 10px; cursor:pointer; font-size:12px }}
nav {{ display:flex; gap:4px; border-bottom:1px solid var(--line); margin-bottom:20px }}
nav a {{ padding:8px 14px; font-size:12px; letter-spacing:.08em; text-transform:uppercase;
  color:var(--ink3); text-decoration:none; border-bottom:2px solid transparent; cursor:pointer }}
nav a.on {{ color:var(--ink); border-bottom-color:var(--blue) }}
section {{ display:none }} section.on {{ display:block }}
.tiles {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:12px }}
.tile {{ background:var(--s2); border:1px solid var(--line); border-radius:10px; padding:14px 16px }}
.tile-num {{ font-size:28px; font-weight:650; font-variant-numeric:tabular-nums }}
.tile-label {{ color:var(--ink2); font-size:13px }}
.tile-sub {{ color:var(--ink3); font-size:11px; margin-top:2px }}
table {{ width:100%; border-collapse:collapse; font-size:13.5px }}
td {{ padding:6px 10px 6px 0; border-bottom:1px solid var(--line); vertical-align:top }}
td.num {{ text-align:right; font-variant-numeric:tabular-nums; width:4ch }}
td.cell-bar {{ width:38% }}
.mono {{ font-family:ui-monospace,Menlo,monospace; font-size:12.5px; white-space:nowrap }}
.dim {{ color:var(--ink2) }}
.flink {{ color:var(--ink); text-decoration:none; border-bottom:1px dotted var(--ink3) }}
.flink:hover {{ color:var(--blue); border-bottom-color:var(--blue) }}
.meter {{ background:var(--s2); border:1px solid var(--line); border-radius:4px; height:12px;
  overflow:hidden }}
.meter-fill {{ height:100% }}
.status.ok {{ color:var(--ok); font-weight:600 }}
.status.warn {{ color:var(--warn); font-weight:600 }}
.chip {{ display:inline-block; background:var(--s2); border:1px solid var(--line);
  border-radius:99px; padding:2px 10px; font-size:12px; margin:2px 2px }}
.note {{ color:var(--ink3); font-size:12px; margin-top:6px }}
.grid2 {{ display:grid; grid-template-columns:1fr 1fr; gap:0 40px }}
@media (max-width:720px) {{ .grid2 {{ grid-template-columns:1fr }} }}
.wrap {{ overflow-x:auto }}
input.filter {{ background:var(--s2); color:var(--ink); border:1px solid var(--line);
  border-radius:6px; padding:6px 12px; font-size:13px; width:280px; max-width:100%;
  margin-bottom:10px }}
input.filter:focus {{ outline:2px solid var(--blue); outline-offset:1px }}
</style></head><body data-gen="{gen_epoch}">
<header><h1>Skill<span style="color:var(--acc)">board</span></h1>
<div><span class="gen" id="age">generated {now}</span>
<button id="th" onclick="t()">theme</button></div></header>

{banner}

<nav>
<a data-tab="overview" class="on">Overview</a>
<a data-tab="memory">Memory<span class="badge{' warn-d' if (days_ago is None or days_ago > 7) else ''}">{mem_total}</span></a>
<a data-tab="skills">Skills<span class="badge">{len(sk)}</span></a>
<a data-tab="plans">Plans<span class="badge">{len(pl)}</span></a>
<a data-tab="setup">Setup</a>
</nav>

<section id="overview" class="on">
<div class="tiles">{tiles_html}</div>
{usage_html}
<h2>Hooks &amp; Plugins</h2>
<div class="grid2"><div><table>{hooks_rows_html}</table></div>
<div>{plugins_html}</div></div>
<p class="note">Regenerates automatically each session start · manual: <span class="mono">dash</span></p>
</section>

<section id="memory">
<div class="grid2"><div>
<table><tr><td>SQLite-index trigger progress</td><td class="num">{corpus}/{TRIGGER}</td>
<td class="cell-bar">{bar(trig_pct)}</td></tr>{src_rows}</table>
<p class="note">Index is disposable — files are the only truth. Refresh: <span class="mono">python3 ~/.claude/scripts/memory-index.py</span></p>
</div><div>
<table><tr><td>Weekly maintenance</td><td colspan="2">{maint}</td></tr>
<tr><td class="dim" colspan="3">{esc(maint_sub)}</td></tr>{brain_rows}</table>
<p class="note">Brain: /remember:process weekly → /remember:evolve</p>
</div></div>
</section>

<section id="skills">
<h2>Plugin skills ({len(plug_sk)})</h2>
<div class="cards">{plug_cards}</div>
<h2>Local skills ({len(loc_sk)})</h2>
<input class="filter" placeholder="filter skills…" oninput="flt(this,'sktab')">
<div class="wrap"><table id="sktab">{skills_rows}</table></div>
<p class="note">Plugin skills ship with skillboard (copy link to share); local skills live only on this machine. Click a local name to open in VS Code.</p>
</section>

<section id="setup">
<h2>What this setup does</h2>
<div class="wrap"><table>{feat_rows}</table></div>
<h2>New machine checklist</h2>
{checklist}
<h2>Recommended plugins &amp; tools</h2>
<div class="wrap"><table>{rec_rows}</table></div>
<p class="note">Status detected at generation time from settings.json + PATH. Copy the shown command to install; nothing installs automatically.</p>
</section>

<section id="plans">
<input class="filter" placeholder="filter plans…" oninput="flt(this,'pltab')">
<div class="wrap"><table id="pltab">{plan_rows}</table></div>
<p class="note">Newest first, across ~/development/.doc and chatbot-pro doc/plans. Click to open.</p>
</section>

<script>
function t(){{const r=document.documentElement,c=r.dataset.theme||
(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
r.dataset.theme=c==='dark'?'light':'dark'}}
function cp(b){{navigator.clipboard.writeText(b.dataset.link).then(()=>{{
const o=b.textContent;b.textContent='copied!';setTimeout(()=>b.textContent=o,1200)}})}}
function flt(inp,id){{const q=inp.value.toLowerCase();
for(const tr of document.getElementById(id).rows)
tr.style.display=tr.textContent.toLowerCase().includes(q)?'':'none'}}
document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{{
document.querySelectorAll('nav a,section').forEach(x=>x.classList.remove('on'));
a.classList.add('on');document.getElementById(a.dataset.tab).classList.add('on');
location.hash=a.dataset.tab}});
const h=location.hash.slice(1);
if(h&&document.getElementById(h)){{document.querySelector('nav a.on').classList.remove('on');
document.querySelector('section.on').classList.remove('on');
document.querySelector(`nav a[data-tab=${{h}}]`).classList.add('on');
document.getElementById(h).classList.add('on')}}
const ageH=(Date.now()/1000-+document.body.dataset.gen)/3600;
if(ageH>24){{const e=document.getElementById('age');
e.classList.add('stale');e.textContent+=` · STALE ${{ageH.toFixed(0)}}h — run: dash`}}
</script></body></html>"""
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(page)
    print(OUT)
    if "--open" in sys.argv:
        import subprocess
        subprocess.run(["open", OUT], check=False)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:  # fail-open: runs inside an async SessionStart hook
        print(f"setup-dashboard error: {e}", file=sys.stderr)
        sys.exit(0)
